version: '3.9'

services:
  app:
    build: .
    container_name: llm_gateway_api
    ports:
      - "8000:8000"
    volumes:
      - ./app/static/images:/app/app/static/images  # Monta im√°genes generadas
    env_file:
      - .env  # Usa todas las claves del entorno desde el .env
    restart: unless-stopped
